### PR TITLE
Replaced `inspect.isclass(...)` with `isinstance(..., type)`

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by isidentical** [comment]
I am not sure what this patch aims, can you explain it?

**Comment by KOLANICH** [comment]
https://github.com/berkerpeksag/astor/commit/51c9e70f1b3a8877cb531ab9c5b1a814eefe7532#commitcomment-36324207

**Comment by KOLANICH** [comment]
In python 3 there are no old-style classes. `(object)` is not needed. I suggest to just drop python 2.

**Comment by berkerpeksag** [comment]
Dropping Python 2 support in a bug fix release is not an option.

**Comment by KOLANICH** [comment]
You can just wait with merging it untill 2020-01-01

**Comment by isidentical** [comment]
@berkerpeksag do astor have a roadmap about dropping py2 support? I guess it will make codebase alot clear

**Comment by berkerpeksag** [comment]
I doubt we are going to drop Python 2 support before reaching to 1.0. Of course, we can drop it earlier if we had to deal with tooling issues again (it was impossible to run tests under 2.6 and 3.2 due to pip's policy changes)

**Pull request closed without merging**
