### PR TITLE
Stop triple quoting strings embedded in function calls

### PR DESCRIPTION
**Pull request by pmaupin**
Reduce the number of strings that get triple-quoted by the new pretty printing logic.

It was fairly aggressive at triple-quoting.  In general, we do not want to triple-quote strings embedded in lists unless they have line feeds in them.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
LGTM, thanks! Do we need to add a test?

**Comment by pmaupin** [comment]
Yes, actually, I should/will, thanks.  I just fixed it quickly at work...

**Comment by pmaupin** [comment]
I've pushed a test that fails on the master and works on this branch.

Thanks,
Pat

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
