### PR TITLE
Move CHANGES to docs/changlog.rst

### PR DESCRIPTION
**Pull request by leonardt**
Addresses https://github.com/berkerpeksag/astor/issues/18
Screenshot (uses default sphinx style because I rendered it locally). The whitespace under multi-line table cells using an `rst` line block is a tiny bit funky, not sure if there's a way around it.
Feel free to squash when merging.

image

### CODE REVIEW

**Comment by leonardt** [comment]
Should consider reversing the order of changes (so that the latest version is first)

**Comment by pmaupin** [comment]
I like the idea of the order reversal; easier to see what's changed recently.

As far as sphinx v github view, they are open (eventually) to making things different on github.  We might want to revisit the main doc; when I initially wrote it, I was having issues here:

https://github.com/github/markup/issues/514

**Comment by pmaupin** [comment]
It's been so long that I forgot all the details about the github rst stuff.  Anyway, they merged my stuff last month, and here's the example I wound up writing about it:

https://github.com/github/markup/blob/master/test/markups/README.directives.rst

**Comment by pmaupin** [comment]
This was already merged into #59, right?

**Comment by pmaupin** [comment]
I will go ahead and make the changes suggested by @berkerpeksag and merge.

Otherwise, the functional changes will outrace the doc...

**Pull request merged**
