### PR TITLE
added missing arguments vistor from Armin's original repo

### PR DESCRIPTION
**Pull request by whyzgeek**
Hi

I found a couple of lines missing from original Armin's code. I needed these as it fails my tests without them. Can you please accept this?

Regards
Whyzgeek

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Thanks for the patch, @whyzgeek. Could you please convert your test to a test case for astor too? We have very few tests for now, it would be great to add some tests. Also, please add your name to AUTHORS. Thanks again!

**Comment by whyzgeek** [comment]
All done, the test is there. :)

**Comment by berkerpeksag** [comment]
Thanks! :) I will apply it shortly.

**Comment by berkerpeksag** [comment]
Merged in https://github.com/berkerpeksag/astor/commit/0d5faf3ac4eebd83c836e788f31c8e7ba8e4a2d4. Will release 0.4.1 soon. Thanks!

**Comment by whyzgeek** [comment]
Thanks for this. However, I noticed that you changed the test. There was a reason, I wrote that test specifically like that. If you run the test with or without those couple of lines, it produces similar results. Hence it doesn't really test the functionality.  To  test this more accurately, you need to pass an arguments node to_source function.

**Comment by berkerpeksag** [comment]
Yeah, I noticed that after pushed the new release, but I was lazy to test it properly :) Will update the test case. Thanks!

**Comment by berkerpeksag** [comment]
Hey, added the test in https://github.com/berkerpeksag/astor/commit/ee7a5ff70bb861d220c255dffc7b0d0cf220c231. Thanks again!

**Pull request closed without merging**
